image: python:3.8

pipelines:
  default:
    - parallel:
        - step:
            name: CI Static Analysis
            caches:
              - pip
            script:
              - apt-get update && apt-get install -y cppcheck
              - pip install pre-commit
              - pip install lizard
              - pre-commit run --all-files
              - lizard ./test/ -V
            after-script:
              - echo "Finalized CI pipeline!"
        - step:
            name: Unit Tests
            script:
              - pip install tox
              - tox
